USE [master]
GO

/****** Object:  Database [qlKhachsan]    Script Date: 11/17/2018 12:14:48 AM ******/
CREATE DATABASE [qlKhachsan]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'qlKhachsan', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\qlKhachsan.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'qlKhachsan_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\qlKhachsan_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [qlKhachsan] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [qlKhachsan].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [qlKhachsan] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [qlKhachsan] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [qlKhachsan] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [qlKhachsan] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [qlKhachsan] SET ARITHABORT OFF 
GO

ALTER DATABASE [qlKhachsan] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [qlKhachsan] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [qlKhachsan] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [qlKhachsan] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [qlKhachsan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [qlKhachsan] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [qlKhachsan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [qlKhachsan] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [qlKhachsan] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [qlKhachsan] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [qlKhachsan] SET  DISABLE_BROKER 
GO

ALTER DATABASE [qlKhachsan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [qlKhachsan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [qlKhachsan] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [qlKhachsan] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [qlKhachsan] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [qlKhachsan] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [qlKhachsan] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [qlKhachsan] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [qlKhachsan] SET  MULTI_USER 
GO

ALTER DATABASE [qlKhachsan] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [qlKhachsan] SET DB_CHAINING OFF 
GO

ALTER DATABASE [qlKhachsan] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [qlKhachsan] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [qlKhachsan] SET  READ_WRITE 
GO

